config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'users/users'
  get 'parkings/index_json'
  resources :parkings
  resources :bookings
  resources :patchphotos
  resources :roles

  root 'index#index'
  resources :properts

  get 'info/socket'
  get 'info/convention'
  get 'info/offer'

end

app/models/patchphoto.rb
class Patchphoto < ActiveRecord::Base
  belongs_to :parking
  dragonfly_accessor  :image
end

app/controllers/patchphotos_controller.rb
class PatchphotosController < ApplicationController
  before_action :set_patchphoto, only: [:show, :edit, :update, :destroy]

  # GET /patchphotos
  # GET /patchphotos.json
  def index
    @patchphotos = Patchphoto.all
  end

  # GET /patchphotos/1
  # GET /patchphotos/1.json
  def show
  end

  # GET /patchphotos/new
  def new
    @patchphoto = Patchphoto.new
  end

  # GET /patchphotos/1/edit
  def edit
  end

  # POST /patchphotos
  # POST /patchphotos.json
  def create
    @patchphoto = Patchphoto.new(patchphoto_params)

    respond_to do |format|
      if @patchphoto.save
        format.html { redirect_to @patchphoto, notice: 'Patchphoto was successfully created.' }
        format.json { render :show, status: :created, location: @patchphoto }
      else
        format.html { render :new }
        format.json { render json: @patchphoto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patchphotos/1
  # PATCH/PUT /patchphotos/1.json
  def update
    respond_to do |format|
      if @patchphoto.update(patchphoto_params)
        format.html { redirect_to @patchphoto, notice: 'Patchphoto was successfully updated.' }
        format.json { render :show, status: :ok, location: @patchphoto }
      else
        format.html { render :edit }
        format.json { render json: @patchphoto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patchphotos/1
  # DELETE /patchphotos/1.json
  def destroy
    @patchphoto.destroy
    respond_to do |format|
      format.html { redirect_to patchphotos_url, notice: 'Patchphoto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patchphoto
      @patchphoto = Patchphoto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patchphoto_params
      params.require(:patchphoto).permit(:parking_id, :image)
    end
end

app/helpers/patchphotos_helper.rb
module PatchphotosHelper
end

app/views/patchphotos/_form.html.slim
= form_for @patchphoto do |f|
  - if @patchphoto.errors.any?
    #error_explanation
      h2 = "#{pluralize(@patchphoto.errors.count, "error")} prohibited this patchphoto from being saved:"
      ul
        - @patchphoto.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :image
    = f.file_field :image, multiple:true
  .field
    = f.label :parking
    = f.text_field :parking
  .actions = f.submit

app/views/patchphotos/edit.html.slim
h1 Editing patchphoto

== render 'form'

= link_to 'Show', @patchphoto
'|
= link_to 'Back', patchphotos_path

app/views/patchphotos/index.html.slim
h1 Listing patchphotos

table
  thead
    tr
      th Patch
      th Parking
      th
      th
      th

  tbody
    - @patchphotos.each do |patchphoto|
      tr
        td = image_tag patchphoto.image.thumb('400x200#').url if patchphoto.image_stored?
        td = patchphoto.parking
        td = link_to 'Show', patchphoto
        td = link_to 'Edit', edit_patchphoto_path(patchphoto)
        td = link_to 'Destroy', patchphoto, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Patchphoto', new_patchphoto_path

app/views/patchphotos/new.html.slim
h1 New patchphoto

== render 'form'

= link_to 'Back', patchphotos_path

app/views/patchphotos/show.html.slim
p#notice = notice

p
  strong Patch:
  = image_tag @patchphoto.image.url
p
  strong Parking:
  = @patchphoto.parking

= link_to 'Edit', edit_patchphoto_path(@patchphoto)
'|
= link_to 'Back', patchphotos_path