config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'users/users'
  get 'parkings/index_json'
  resources :parkings
  resources :bookings
  resources :patchphotos
  resources :roles

  root 'index#index'
  resources :properts

  get 'info/socket'
  get 'info/convention'
  get 'info/offer'

end

app/views/inc/_admin_sidebar.html.slim
#sidebar-wrapper
  ul.sidebar-nav
    li
      a[href="#"] Роли

app/views/inc/_footer.html.slim
footer.container-fluid.navbar-inverse.navbar-fixed-bottom.navbar
  .row
    ul.list-unstyled
      li.col-lg-2
        a.button href="#" Подать объявление
      li.col-lg-2
        a.button href=root_url Главная
      li.col-lg-2
        a.button href="#" Помощь
      li.col-lg-2
        a.button href="#" Безопасность
      li.col-lg-2
        a.button href="#" Реклама на сайте
      li.col-lg-2
        a.button href="#" О компании
  .row
    .text-justify
        p
          | ©
          = InfoHelper::NAME_SITE
          |  — сайт объявлений. Использование сайта, в том числе подача объявлений, означает согласие с
          a[href=info_convention_path]  пользовательским соглашением.
          |  Оплачивая услуги на сайте, вы принимаете
          a[href=info_offer_url]  оферту
          |.

app/views/inc/_header.html.slim
.navbar.navbar-default#menu[role="navigation"]
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed[type="button" data-toggle="collapse" data-target="#menu"]
        span.sr-only Переключение навигации
        span.icon-bar
        span.icon-bar
        span.icon-bar
    .navbar-collapse.collapsed#menu
      .col-md-8.col-lg-8
        = render 'inc/search'
      .col-md-4.col-lg-4
        ul.nav.navbar-nav.navbar-right
          li
              =link_to "Добавить", new_parking_path
          li
            -if user_signed_in?
              span
                |Здравствуйте
                =current_user.email
            -else
              =link_to 'Войти', new_user_session_path



//Todo переработать логотип и воткнуть
//nav.container-fluid.navbar-default#head
  .navbar-header
    img.img_size.img-responsive[src="/assets/Parking.svg/" alt="Parking"]
  ul.nav.navbar-default.col-md-10.col-lg-10
    li
      =render 'inc/search'

app/views/inc/_search.html.slim
//Начало формы поиска
form.navbar-form.navbar-left[role="search"]
    .input-group
      span.btn-warning.input-group-addon.orange
        span.glyphicon.glyphicon-map-marker
      input.form-control#geocomplete[placeholder="Ваш город..." type="text" autocomplete="off"]
      span.btn-warning.input-group-addon.orange#search
        span.glyphicon.glyphicon-search



//Форма дополнительных параметров
  .form-group
    //выбор города
    .input-group-btn.dop_panel
      .btn.btn-default.dropdown-toggle[type="button" data-toggle="dropdown"]
        span#selectCity[id_city=0]
          |Не выбрано
        .span.caret
      ul.dropdown-menu#city

    .input-group-btn.dop_panel
      .btn.btn-default.dropdown-toggle[type="button" data-toggle="dropdown"]
        span#selectDestrict[id_destrict=0]
          |Не выбрано
        .span.caret
      ul.dropdown-menu#destrict

    .input-group-btn.dop_panel
      .btn.btn-default.dropdown-toggle[type="button" data-toggle="dropdown"]
        span#selectPeriod[id_period=0]
          |Не выбрано
        .span.caret
      ul.dropdown-menu#period

    .input-group-btn.dop_panel
      .btn.btn-default.dropdown-toggle[type="button" data-toggle="dropdown"]
        span#selectTypeParking[id_typeparking]
          |Не выбрано
        .span.caret
      ul.dropdown-menu#typeparking

    //=select_tag "select", options_for_select(@sities)
    //=select_tag "select", options_for_select(@districts)
    //=select_tag "select", options_for_select(@periods)
    //=select_tag "select", options_for_select(@typeparkings)

  //Окончание формы поиска


//.panel П
//.panel 16
//.col-lg-2.col-md-2 Личный кабинет

app/views/inc/_sidebar.html.slim
.col-xs-12.col-lg-3
  .list-group
    .list-group-item
      =link_to "Роль", roles_path
    .list-group-item
      =link_to "Парковки", parkings_path