config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'users/users'
  get 'parkings/index_json'
  resources :parkings
  resources :bookings
  resources :patchphotos
  resources :roles

  root 'index#index'
  resources :properts

  get 'info/socket'
  get 'info/convention'
  get 'info/offer'

end

app/models/role.rb
class Role < ActiveRecord::Base
    has_many :users
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]
  layout 'admin'

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:code, :name, :descriptions)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.slim
= form_for @role do |f|
  - if @role.errors.any?
    #error_explanation
      h2 = "#{pluralize(@role.errors.count, "error")} prohibited this role from being saved:"
      ul
        - @role.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :code
    = f.text_field :code
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :descriptions
    = f.text_area :descriptions
  .actions = f.submit

app/views/roles/edit.html.slim
h1 Editing role

== render 'form'

= link_to 'Открыть', @role
'|
= link_to 'Назад', roles_path

app/views/roles/index.html.slim
h1 Список ролей

table.table.table-striped
  thead
    tr
      th Код
      th Наименование
      th Описание
      th
      th
      th

  tbody
    - @roles.each do |role|
      tr
        td = role.code
        td = role.name
        td = role.descriptions
        td = link_to 'Открыть', role, class:"btn btn-success"
        td = link_to 'Редактировать', edit_role_path(role), class:"btn btn-warning"
        td = link_to 'Удалить', role, data: {:confirm => 'Вы уверены?'}, :method => :delete, class:"btn btn-danger"

br

= link_to 'Новая роль', new_role_path, class:"btn btn-success"

app/views/roles/new.html.slim
h1 New role

== render 'form'

= link_to 'Назад', roles_path

app/views/roles/show.html.slim
p#notice = notice

p
  strong Code:
  = @role.code
p
  strong Name:
  = @role.name
p
  strong Descriptions:
  = @role.descriptions

= link_to 'Редактировать', edit_role_path(@role)
'|
= link_to 'Назад', roles_path